Skillz4Killz/gamer-eris

- README.md
- package-lock.json
- package.json
- src/commands/owner/setname.ts
- src/database/mongodb.ts
- src/database/schemas/guild.ts
- src/index.ts
- src/lib/structures/GamerClient.ts
- src/lib/structures/Monitor.ts
This PR adds the Monitor store functionality, adds the setname command, mongodb/mongoose added as deps and creates the schema for the entire guild table
> Monitors and MongoDB

- src/commands/gif.ts
Requesting pull - Added gif.ts
> Added gif.ts

- i18n/en-US/gaming/twitch.json
- src/events/twitchAlert.ts
This PR should add a event that will handle sending twitch alerts to all necessary channels.
> Twitch send alerts

- i18n/en-US/network/networkcreate.json
- i18n/en-US/network/networkfollow.json
- i18n/en-US/network/reaction.json
- src/commands/eventedit.ts
- src/commands/help.ts
- src/commands/networkcreate.ts
- src/commands/networkfollow.ts
- src/constants/emojis.ts
- src/database/mongodb.ts
- src/database/schemas/guild.ts
- src/database/schemas/user.ts
- src/events/messageReactionAdd.ts
- src/lib/types/settings.ts
- src/lib/utils/discord.ts
- src/monitors/wallpost.ts
This PR adds the social network feature into gamer.
> Add social network feature

- .github/workflows/nodejs.yml
> Fix deployment action

- src/commands/reactionroleadd.ts
Fixes "Unknown Channel" by checking if the guild has a channel with that ID before fetching the message.
> fix(reactionroleadd.ts): Fixes the "Unknown Channel" when executing the command.

- src/commands/verify.ts
I'm sorry, I did not notice this. This completely does not work, it stills throws the error (Unhandled Promise Rejection). Added it to other message.delete's.
> hotfix(verify.ts): In fact, .catch() alone does not work.

- src/events/messageReactionAdd.ts
Forgot to create a new branch on my fork ecks dee.
> fix(messageReactionAdd.ts): Catch more errors on delete.

- README.md
The README is over level 9000 lol
> There, center + small image

- i18n/de_DE/basic/user.json
- i18n/en-US/moderation/note.json
- src/commands/basic/help.ts
- src/commands/moderation/note.ts
> fixed note command, add new file

- src/commands/roles/roleinfo.ts
bring back the old member count, if not let me know
> roleinfo fix

- i18n/en-US/utility/bots.json
- i18n/en-US/vip/bots.json
- src/commands/basic/help.ts
- src/commands/vip/bots.ts
changes the .bots command to vip
> change the bots command to vip

- src/constants/profiles.ts
Change default bg, looks a lot cleaner
> change default bg

- src/commands/settings/reset.ts
fixed the reset command where u can still analyze
> fix reset command

- i18n/en-US/fun/raphtalia.json
- src/commands/basic/help.ts
- src/commands/fun/raphtalia.ts
Added Fun Command Raphtalia, like the kanna
> add raphtalia command

- README.md
"www" were missing in the typescript website link.
> fix typescript link broken

- i18n/en-US/vip/memberrole.json
- src/commands/fun/slots.ts
- src/commands/vip/bots.ts
- src/commands/vip/memberrole.ts
- src/constants/emojis.ts
add new emotes to slots
change the bots command into Mod and Admin -> create now a message instead a message
> add new stuff

- i18n/en-US/vip/members.json
- src/commands/basic/help.ts
- src/commands/vip/memberrole.ts
- src/commands/vip/members.ts
> add members for VIP

- i18n/en-US/fun/mavis.json
- src/commands/basic/help.ts
- src/commands/fun/mavis.ts
added fun command .mavis
Love you skillz <3 :D
> added fun command .mavis

- i18n/en-US/vip/listallroles.json
- src/commands/basic/help.ts
- src/commands/basic/user.ts
- src/commands/vip/listallroles.ts
Fix the ui command with deleted roles
add a new VIP command which shows every role in ur server with ID -> with members soon
> fix .ui, add new command

- i18n/en-US/settings/setlogs.json
- i18n/en-US/settings/setvoicelogs.json
- src/commands/basic/help.ts
- src/commands/settings/setvoicelogs.ts
- src/database/schemas/guild.ts
- src/events/voiceChannelJoin.ts
- src/events/voiceChannelLeave.ts
- src/lib/types/settings.ts
- src/lib/utils/scripts.ts
> add new logs

- src/commands/utility/quote.ts
If quoted message has embeds, still show content of it
> Update quote.ts to show message content

- i18n/en-US/fun/mavis.json
- i18n/en-US/settings/sethibye.json
> fix some typos
